// Auto-generated. Do not edit!

// (in-package ros_tutorial.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class counterFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.complete_percent = null;
    }
    else {
      if (initObj.hasOwnProperty('complete_percent')) {
        this.complete_percent = initObj.complete_percent
      }
      else {
        this.complete_percent = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type counterFeedback
    // Serialize message field [complete_percent]
    bufferOffset = _serializer.float32(obj.complete_percent, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type counterFeedback
    let len;
    let data = new counterFeedback(null);
    // Deserialize message field [complete_percent]
    data.complete_percent = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ros_tutorial/counterFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c375bca28786480387684f5bccabc0b5';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float32 complete_percent
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new counterFeedback(null);
    if (msg.complete_percent !== undefined) {
      resolved.complete_percent = msg.complete_percent;
    }
    else {
      resolved.complete_percent = 0.0
    }

    return resolved;
    }
};

module.exports = counterFeedback;
