// Auto-generated. Do not edit!

// (in-package ros_tutorial.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class counterGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.goal_num = null;
    }
    else {
      if (initObj.hasOwnProperty('goal_num')) {
        this.goal_num = initObj.goal_num
      }
      else {
        this.goal_num = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type counterGoal
    // Serialize message field [goal_num]
    bufferOffset = _serializer.int32(obj.goal_num, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type counterGoal
    let len;
    let data = new counterGoal(null);
    // Deserialize message field [goal_num]
    data.goal_num = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ros_tutorial/counterGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '99fc8ea054f24b75e22a1cacf948e8fe';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 goal_num
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new counterGoal(null);
    if (msg.goal_num !== undefined) {
      resolved.goal_num = msg.goal_num;
    }
    else {
      resolved.goal_num = 0
    }

    return resolved;
    }
};

module.exports = counterGoal;
