; Auto-generated. Do not edit!


(cl:in-package ros_tutorial-msg)


;//! \htmlinclude counterFeedback.msg.html

(cl:defclass <counterFeedback> (roslisp-msg-protocol:ros-message)
  ((complete_percent
    :reader complete_percent
    :initarg :complete_percent
    :type cl:float
    :initform 0.0))
)

(cl:defclass counterFeedback (<counterFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <counterFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'counterFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ros_tutorial-msg:<counterFeedback> is deprecated: use ros_tutorial-msg:counterFeedback instead.")))

(cl:ensure-generic-function 'complete_percent-val :lambda-list '(m))
(cl:defmethod complete_percent-val ((m <counterFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ros_tutorial-msg:complete_percent-val is deprecated.  Use ros_tutorial-msg:complete_percent instead.")
  (complete_percent m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <counterFeedback>) ostream)
  "Serializes a message object of type '<counterFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'complete_percent))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <counterFeedback>) istream)
  "Deserializes a message object of type '<counterFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'complete_percent) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<counterFeedback>)))
  "Returns string type for a message object of type '<counterFeedback>"
  "ros_tutorial/counterFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'counterFeedback)))
  "Returns string type for a message object of type 'counterFeedback"
  "ros_tutorial/counterFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<counterFeedback>)))
  "Returns md5sum for a message object of type '<counterFeedback>"
  "c375bca28786480387684f5bccabc0b5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'counterFeedback)))
  "Returns md5sum for a message object of type 'counterFeedback"
  "c375bca28786480387684f5bccabc0b5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<counterFeedback>)))
  "Returns full string definition for message of type '<counterFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 complete_percent~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'counterFeedback)))
  "Returns full string definition for message of type 'counterFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 complete_percent~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <counterFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <counterFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'counterFeedback
    (cl:cons ':complete_percent (complete_percent msg))
))
