; Auto-generated. Do not edit!


(cl:in-package ros_tutorial-msg)


;//! \htmlinclude counterResult.msg.html

(cl:defclass <counterResult> (roslisp-msg-protocol:ros-message)
  ((finish
    :reader finish
    :initarg :finish
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass counterResult (<counterResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <counterResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'counterResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ros_tutorial-msg:<counterResult> is deprecated: use ros_tutorial-msg:counterResult instead.")))

(cl:ensure-generic-function 'finish-val :lambda-list '(m))
(cl:defmethod finish-val ((m <counterResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ros_tutorial-msg:finish-val is deprecated.  Use ros_tutorial-msg:finish instead.")
  (finish m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <counterResult>) ostream)
  "Serializes a message object of type '<counterResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'finish) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <counterResult>) istream)
  "Deserializes a message object of type '<counterResult>"
    (cl:setf (cl:slot-value msg 'finish) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<counterResult>)))
  "Returns string type for a message object of type '<counterResult>"
  "ros_tutorial/counterResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'counterResult)))
  "Returns string type for a message object of type 'counterResult"
  "ros_tutorial/counterResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<counterResult>)))
  "Returns md5sum for a message object of type '<counterResult>"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'counterResult)))
  "Returns md5sum for a message object of type 'counterResult"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<counterResult>)))
  "Returns full string definition for message of type '<counterResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'counterResult)))
  "Returns full string definition for message of type 'counterResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <counterResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <counterResult>))
  "Converts a ROS message object to a list"
  (cl:list 'counterResult
    (cl:cons ':finish (finish msg))
))
