; Auto-generated. Do not edit!


(cl:in-package ros_tutorial-msg)


;//! \htmlinclude counterGoal.msg.html

(cl:defclass <counterGoal> (roslisp-msg-protocol:ros-message)
  ((goal_num
    :reader goal_num
    :initarg :goal_num
    :type cl:integer
    :initform 0))
)

(cl:defclass counterGoal (<counterGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <counterGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'counterGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ros_tutorial-msg:<counterGoal> is deprecated: use ros_tutorial-msg:counterGoal instead.")))

(cl:ensure-generic-function 'goal_num-val :lambda-list '(m))
(cl:defmethod goal_num-val ((m <counterGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ros_tutorial-msg:goal_num-val is deprecated.  Use ros_tutorial-msg:goal_num instead.")
  (goal_num m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <counterGoal>) ostream)
  "Serializes a message object of type '<counterGoal>"
  (cl:let* ((signed (cl:slot-value msg 'goal_num)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <counterGoal>) istream)
  "Deserializes a message object of type '<counterGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_num) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<counterGoal>)))
  "Returns string type for a message object of type '<counterGoal>"
  "ros_tutorial/counterGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'counterGoal)))
  "Returns string type for a message object of type 'counterGoal"
  "ros_tutorial/counterGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<counterGoal>)))
  "Returns md5sum for a message object of type '<counterGoal>"
  "99fc8ea054f24b75e22a1cacf948e8fe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'counterGoal)))
  "Returns md5sum for a message object of type 'counterGoal"
  "99fc8ea054f24b75e22a1cacf948e8fe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<counterGoal>)))
  "Returns full string definition for message of type '<counterGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 goal_num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'counterGoal)))
  "Returns full string definition for message of type 'counterGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 goal_num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <counterGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <counterGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'counterGoal
    (cl:cons ':goal_num (goal_num msg))
))
