// Generated by gencpp from file ros_tutorial/add.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIAL_MESSAGE_ADD_H
#define ROS_TUTORIAL_MESSAGE_ADD_H

#include <ros/service_traits.h>


#include <ros_tutorial/addRequest.h>
#include <ros_tutorial/addResponse.h>


namespace ros_tutorial
{

struct add
{

typedef addRequest Request;
typedef addResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add
} // namespace ros_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_tutorial::add > {
  static const char* value()
  {
    return "13918c933de1bcb345f89e4d03db37f4";
  }

  static const char* value(const ::ros_tutorial::add&) { return value(); }
};

template<>
struct DataType< ::ros_tutorial::add > {
  static const char* value()
  {
    return "ros_tutorial/add";
  }

  static const char* value(const ::ros_tutorial::add&) { return value(); }
};


// service_traits::MD5Sum< ::ros_tutorial::addRequest> should match
// service_traits::MD5Sum< ::ros_tutorial::add >
template<>
struct MD5Sum< ::ros_tutorial::addRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tutorial::add >::value();
  }
  static const char* value(const ::ros_tutorial::addRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tutorial::addRequest> should match
// service_traits::DataType< ::ros_tutorial::add >
template<>
struct DataType< ::ros_tutorial::addRequest>
{
  static const char* value()
  {
    return DataType< ::ros_tutorial::add >::value();
  }
  static const char* value(const ::ros_tutorial::addRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_tutorial::addResponse> should match
// service_traits::MD5Sum< ::ros_tutorial::add >
template<>
struct MD5Sum< ::ros_tutorial::addResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tutorial::add >::value();
  }
  static const char* value(const ::ros_tutorial::addResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tutorial::addResponse> should match
// service_traits::DataType< ::ros_tutorial::add >
template<>
struct DataType< ::ros_tutorial::addResponse>
{
  static const char* value()
  {
    return DataType< ::ros_tutorial::add >::value();
  }
  static const char* value(const ::ros_tutorial::addResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_TUTORIAL_MESSAGE_ADD_H
