// Generated by gencpp from file ros_tutorial/addRequest.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIAL_MESSAGE_ADDREQUEST_H
#define ROS_TUTORIAL_MESSAGE_ADDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tutorial
{
template <class ContainerAllocator>
struct addRequest_
{
  typedef addRequest_<ContainerAllocator> Type;

  addRequest_()
    : A(0)
    , B(0)  {
    }
  addRequest_(const ContainerAllocator& _alloc)
    : A(0)
    , B(0)  {
  (void)_alloc;
    }



   typedef int32_t _A_type;
  _A_type A;

   typedef int32_t _B_type;
  _B_type B;





  typedef boost::shared_ptr< ::ros_tutorial::addRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tutorial::addRequest_<ContainerAllocator> const> ConstPtr;

}; // struct addRequest_

typedef ::ros_tutorial::addRequest_<std::allocator<void> > addRequest;

typedef boost::shared_ptr< ::ros_tutorial::addRequest > addRequestPtr;
typedef boost::shared_ptr< ::ros_tutorial::addRequest const> addRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tutorial::addRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tutorial::addRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_tutorial::addRequest_<ContainerAllocator1> & lhs, const ::ros_tutorial::addRequest_<ContainerAllocator2> & rhs)
{
  return lhs.A == rhs.A &&
    lhs.B == rhs.B;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_tutorial::addRequest_<ContainerAllocator1> & lhs, const ::ros_tutorial::addRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial::addRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial::addRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial::addRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial::addRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial::addRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial::addRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tutorial::addRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "623c199892ad84e046e039a21a0e0c11";
  }

  static const char* value(const ::ros_tutorial::addRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x623c199892ad84e0ULL;
  static const uint64_t static_value2 = 0x46e039a21a0e0c11ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tutorial::addRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tutorial/addRequest";
  }

  static const char* value(const ::ros_tutorial::addRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tutorial::addRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 A\n"
"int32 B\n"
;
  }

  static const char* value(const ::ros_tutorial::addRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tutorial::addRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
      stream.next(m.B);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tutorial::addRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tutorial::addRequest_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<int32_t>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<int32_t>::stream(s, indent + "  ", v.B);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TUTORIAL_MESSAGE_ADDREQUEST_H
