// Generated by gencpp from file ros_tutorial/counterFeedback.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIAL_MESSAGE_COUNTERFEEDBACK_H
#define ROS_TUTORIAL_MESSAGE_COUNTERFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tutorial
{
template <class ContainerAllocator>
struct counterFeedback_
{
  typedef counterFeedback_<ContainerAllocator> Type;

  counterFeedback_()
    : complete_percent(0.0)  {
    }
  counterFeedback_(const ContainerAllocator& _alloc)
    : complete_percent(0.0)  {
  (void)_alloc;
    }



   typedef float _complete_percent_type;
  _complete_percent_type complete_percent;





  typedef boost::shared_ptr< ::ros_tutorial::counterFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tutorial::counterFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct counterFeedback_

typedef ::ros_tutorial::counterFeedback_<std::allocator<void> > counterFeedback;

typedef boost::shared_ptr< ::ros_tutorial::counterFeedback > counterFeedbackPtr;
typedef boost::shared_ptr< ::ros_tutorial::counterFeedback const> counterFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tutorial::counterFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tutorial::counterFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_tutorial::counterFeedback_<ContainerAllocator1> & lhs, const ::ros_tutorial::counterFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.complete_percent == rhs.complete_percent;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_tutorial::counterFeedback_<ContainerAllocator1> & lhs, const ::ros_tutorial::counterFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial::counterFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial::counterFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial::counterFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial::counterFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial::counterFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial::counterFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tutorial::counterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c375bca28786480387684f5bccabc0b5";
  }

  static const char* value(const ::ros_tutorial::counterFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc375bca287864803ULL;
  static const uint64_t static_value2 = 0x87684f5bccabc0b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tutorial::counterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tutorial/counterFeedback";
  }

  static const char* value(const ::ros_tutorial::counterFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tutorial::counterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 complete_percent\n"
"\n"
;
  }

  static const char* value(const ::ros_tutorial::counterFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tutorial::counterFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.complete_percent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct counterFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tutorial::counterFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tutorial::counterFeedback_<ContainerAllocator>& v)
  {
    s << indent << "complete_percent: ";
    Printer<float>::stream(s, indent + "  ", v.complete_percent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TUTORIAL_MESSAGE_COUNTERFEEDBACK_H
